# Generated by Django 3.1 on 2022-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('event_type', models.IntegerField(choices=[(0, 'Task Claimed'), (1, 'Task Comment'), (2, 'Submission Approved'), (3, 'Submission Rejected'), (4, 'Bug Rejected'), (5, 'Idea Rejected')], primary_key=True, serialize=False)),
                ('permitted_params', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=400)),
                ('template', models.CharField(max_length=4000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
