# Generated by Django 3.1 on 2022-03-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'Task Claimed'), (1, 'Task Comment'), (2, 'Submission Approved'), (3, 'Submission Rejected')])),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.notification')),
                ('title', models.CharField(max_length=400)),
                ('template', models.CharField(max_length=4000)),
            ],
            bases=('notification.notification',),
        ),
    ]
